### ISSUE TITLE
Linux Compilation Instructions Fail

### ISSUE THREAD

**Issue by Hi-ImKyle** [Bionus/imgbrd-grabber#2092]
**Bug description**

Over on [the docs](https://bionus.github.io/imgbrd-grabber/docs/compilation.html), the Linux instructions are just as simple as 
> Shortcut: just run ./build.sh at the root of the repository, and it will build everything for you.

So I did that and it fails at 61% "Built target lib"

**Steps to reproduce**

1. Clone repo to a local directory
2. Run `./build.sh`
3. Wait for error

**Expected behaviour**

For it to build.

**Context**

Here is the full output of the build from clone to error.
```
root@UbuntuBionic /home/grabber $ git clone --recursive https://github.com/Bionus/imgbrd-grabber
Cloning into 'imgbrd-grabber'...
remote: Enumerating objects: 97, done.
remote: Counting objects: 100% (97/97), done.
remote: Compressing objects: 100% (71/71), done.
remote: Total 36163 (delta 29), reused 60 (delta 22), pack-reused 36066
Receiving objects: 100% (36163/36163), 17.28 MiB | 13.37 MiB/s, done.
Resolving deltas: 100% (27122/27122), done.
Submodule 'cmake/cotire' (https://github.com/sakra/cotire.git) registered for path 'src/cmake/cotire'
Submodule 'cmake/qt-android-cmake' (https://github.com/LaurentGomila/qt-android-cmake.git) registered for path 'src/cmake/qt-android-cmake'
Submodule 'tests/src/vendor/catch' (https://github.com/catchorg/Catch2.git) registered for path 'src/tests/src/vendor/catch'
Cloning into '/home/grabber/imgbrd-grabber/src/cmake/cotire'...
remote: Enumerating objects: 18, done.
remote: Counting objects: 100% (18/18), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 913 (delta 6), reused 14 (delta 6), pack-reused 895
Receiving objects: 100% (913/913), 600.92 KiB | 1.78 MiB/s, done.
Resolving deltas: 100% (452/452), done.
Cloning into '/home/grabber/imgbrd-grabber/src/cmake/qt-android-cmake'...
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 103 (delta 2), reused 5 (delta 2), pack-reused 92
Receiving objects: 100% (103/103), 58.48 KiB | 665.00 KiB/s, done.
Resolving deltas: 100% (54/54), done.
Cloning into '/home/grabber/imgbrd-grabber/src/tests/src/vendor/catch'...
remote: Enumerating objects: 189, done.
remote: Counting objects: 100% (189/189), done.
remote: Compressing objects: 100% (130/130), done.
remote: Total 28589 (delta 81), reused 113 (delta 59), pack-reused 28400
Receiving objects: 100% (28589/28589), 17.95 MiB | 14.90 MiB/s, done.
Resolving deltas: 100% (19992/19992), done.
Submodule path 'src/cmake/cotire': checked out '391bf6b7609e14f5976bd5247b68d63cbf8d4d12'
Submodule path 'src/cmake/qt-android-cmake': checked out '250fdb2caac3413ce9b31e135a36034668e50c90'
Submodule path 'src/tests/src/vendor/catch': checked out '1967feac498795615d512d1de43bf2140575e597'
root@UbuntuBionic /home/grabber $ cd imgbrd-grabber/
root@UbuntuBionic /home/grabber/imgbrd-grabber $ chmod +x build.sh
root@UbuntuBionic /home/grabber/imgbrd-grabber $ ./build.sh
E: Unable to correct problems, you have held broken packages.
/home/grabber/imgbrd-grabber/build /home/grabber/imgbrd-grabber
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring for version '7.3.2'
-- Configuring for platform 'x86' (x86_64)
-- Compiling with SSL support
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.2n")
-- OpenSSL version: 1.0.2n
-- OpenSSL include dir: /usr/include
-- OpenSSL libraries: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/grabber/imgbrd-grabber/build
Scanning dependencies of target sites_modules
Scanning dependencies of target lib_autogen
[  1%] Installing npm packages...
[  1%] Automatic MOC, UIC and RCC for target lib
loadDevDep:xml2js → get   ▀ ╢█████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDevDep:xml2js → resol ▐ ╢█████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
npm WARN deprecated tslint@6.1.2: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.
loadDevDep:xml2js → after ▐ ╢█████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
[  1%] Built target lib_autogen
loadDep:jest-get-type → r ▄ ╢█████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
[  1%] Building CXX object lib/CMakeFiles/lib.dir/src/analytics.cpp.o
[  1%] Building CXX object lib/CMakeFiles/lib.dir/src/auth/auth-hash-field.cpp.o
[  3%] Building CXX object lib/CMakeFiles/lib.dir/src/auth/auth-const-field.cpp.o
[  3%] Building CXX object lib/CMakeFiles/lib.dir/src/auth/auth-field.cpp.o
[  3%] Building CXX object lib/CMakeFiles/lib.dir/src/auth/http-auth.cpp.o
[  3%] Building CXX object lib/CMakeFiles/lib.dir/src/auth/auth.cpp.o
[  4%] Building CXX object lib/CMakeFiles/lib.dir/src/auth/field-auth.cpp.o
loadDep:@types/yargs-pars ▄ ╢█████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
[  6%] Building CXX object lib/CMakeFiles/lib.dir/src/auth/oauth2-auth.cpp.o
[  6%] Building CXX object lib/CMakeFiles/lib.dir/src/auth/url-auth.cpp.o
[  6%] Building CXX object lib/CMakeFiles/lib.dir/src/commands/commands.cpp.o
loadDep:@types/node → req ▐ ╢██████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:@types/node → get ▌ ╢██████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
[  7%] Building CXX object lib/CMakeFiles/lib.dir/src/danbooru-downloader-importer.cpp.o
loadDep:@types/node → net ▀ ╢██████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:jest-cli → reques ▀ ╢████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:jest-cli → resolv ▀ ╢████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:jest-cli → get    ▀ ╢████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine @jest/core@26.4.1: wanted: {"node":">= 10.14.2"} (current: {"node":"8.10.0","npm":"3.5.2"})
loadDep:jest-cli → afterA ▄ ╢████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine @jest/types@26.3.0: wanted: {"node":">= 10.14.2"} (current: {"node":"8.10.0","npm":"3.5.2"})
loadDep:strip-ansi → requ ▄ ╢████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:strip-ansi → netw ▐ ╢████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine jest-config@26.4.1: wanted: {"node":">= 10.14.2"} (current: {"node":"8.10.0","npm":"3.5.2"})
WARN engine @jest/test-result@26.3.0: wanted: {"node":">= 10.14.2"} (current: {"node":"8.10.0","npm":"3.5.2"})
WARN engine jest-changed-files@26.3.0: wanted: {"node":">= 10.14.2"} (current: {"node":"8.10.0","npm":"3.5.2"})
WARN engine jest-regex-util@26.0.0: wanted: {"node":">= 10.14.2"} (current: {"node":"8.10.0","npm":"3.5.2"})
WARN engine jest-watcher@26.3.0: wanted: {"node":">= 10.14.2"} (current: {"node":"8.10.0","npm":"3.5.2"})
loadDep:strip-ansi → cach ▐ ╢████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine jest-runtime@26.4.1: wanted: {"node":">= 10.14.2"} (current: {"node":"8.10.0","npm":"3.5.2"})
WARN engine jest-message-util@26.3.0: wanted: {"node":">= 10.14.2"} (current: {"node":"8.10.0","npm":"3.5.2"})
WARN engine @jest/transform@26.3.0: wanted: {"node":">= 10.14.2"} (current: {"node":"8.10.0","npm":"3.5.2"})
WARN engine jest-resolve@26.4.0: wanted: {"node":">= 10.14.2"} (current: {"node":"8.10.0","npm":"3.5.2"})
WARN engine @jest/reporters@26.4.1: wanted: {"node":">= 10.14.2"} (current: {"node":"8.10.0","npm":"3.5.2"})
WARN engine jest-validate@26.4.0: wanted: {"node":">= 10.14.2"} (current: {"node":"8.10.0","npm":"3.5.2"})
loadDep:strip-ansi → get  ▀ ╢████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine jest-haste-map@26.3.0: wanted: {"node":">= 10.14.2"} (current: {"node":"8.10.0","npm":"3.5.2"})
WARN engine jest-resolve-dependencies@26.4.1: wanted: {"node":">= 10.14.2"} (current: {"node":"8.10.0","npm":"3.5.2"})
WARN engine jest-util@26.3.0: wanted: {"node":">= 10.14.2"} (current: {"node":"8.10.0","npm":"3.5.2"})
loadDep:strip-ansi → addN ▄ ╢████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
[ 11%] Building CXX object lib/CMakeFiles/lib.dir/src/downloader/download-query-manager.cpp.o
loadDep:strip-ansi → afte ▄ ╢████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
[ 11%] Building CXX object lib/CMakeFiles/lib.dir/src/downloader/download-queue.cpp.o
WARN engine @jest/types@26.3.0: wanted: {"node":">= 10.14.2"} (current: {"node":"8.10.0","npm":"3.5.2"})
loadDep:@types/istanbul-r ▀ ╢████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine @jest/types@26.3.0: wanted: {"node":">= 10.14.2"} (current: {"node":"8.10.0","npm":"3.5.2"})
loadDep:stack-utils → aft ▄ ╢████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:stack-utils → net ▌ ╢████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:stack-utils → net ▀ ╢████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine stack-utils@2.0.2: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"3.5.2"})
loadDep:js-tokens → after ▐ ╢████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:supports-color →  ▌ ╢████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
[ 14%] Building CXX object lib/CMakeFiles/lib.dir/src/downloader/image-save-result.cpp.o
loadDep:color-convert → a ▐ ╢████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:fill-range → requ ▄ ╢████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:fill-range → 304  ▌ ╢████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:is-number → reque ▄ ╢████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine @jest/types@26.3.0: wanted: {"node":">= 10.14.2"} (current: {"node":"8.10.0","npm":"3.5.2"})
loadDep:is-ci → get       ▌ ╢████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:@jest/types → res ▄ ╢████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine @jest/types@26.3.0: wanted: {"node":">= 10.14.2"} (current: {"node":"8.10.0","npm":"3.5.2"})
WARN engine chalk@4.1.0: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"3.5.2"})
loadDep:node-notifier → 3 ▌ ╢████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:node-notifier → r ▌ ╢████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
[ 17%] Building CXX object lib/CMakeFiles/lib.dir/src/filename/ast/filename-node-condition-token.cpp.o
loadDep:node-notifier → m ▀ ╢████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine v8-to-istanbul@5.0.1: wanted: {"node":">=10.10.0"} (current: {"node":"8.10.0","npm":"3.5.2"})
loadDep:node-notifier → a ▄ ╢████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:node-notifier → a ▄ ╢████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:@bcoe/v8-coverage ▄ ╢████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine @jest/types@26.3.0: wanted: {"node":">= 10.14.2"} (current: {"node":"8.10.0","npm":"3.5.2"})
[ 19%] Building CXX object lib/CMakeFiles/lib.dir/src/filename/ast/filename-node-root.cpp.o
loadDep:ansi-styles       ▐ ╢████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine @jest/types@26.3.0: wanted: {"node":">= 10.14.2"} (current: {"node":"8.10.0","npm":"3.5.2"})
WARN engine chalk@4.1.0: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"3.5.2"})
loadDep:write-file-atomic ▐ ╢████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:source-map → get  ▄ ╢████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
[ 20%] Building CXX object lib/CMakeFiles/lib.dir/src/filename/ast/filename-visitor-base.cpp.o
loadDep:source-map → afte ▐ ╢████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
[ 22%] Building CXX object lib/CMakeFiles/lib.dir/src/filename/filename-condition-visitor.cpp.o
[ 22%] Building CXX object lib/CMakeFiles/lib.dir/src/filename/filename-execution-visitor.cpp.o
loadDep:@babel/code-frame ▐ ╢████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
[ 22%] Building CXX object lib/CMakeFiles/lib.dir/src/filename/filename-resolution-visitor.cpp.o
loadDep:@babel/helper-spl ▄ ╢████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:minimist → mapToR ▌ ╢████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:path-parse → requ ▐ ╢████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:resolve-from → ad ▌ ╢████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
npm ERR! Linux 4.15.0-112-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/grabber/imgbrd-grabber/src/sites/npm-debug.log
sites/CMakeFiles/sites_modules.dir/build.make:60: recipe for target 'sites/NPM_modules' failed
make[3]: *** [sites/NPM_modules] Error 1
CMakeFiles/Makefile2:908: recipe for target 'sites/CMakeFiles/sites_modules.dir/all' failed
make[2]: *** [sites/CMakeFiles/sites_modules.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
[ 26%] Building CXX object lib/CMakeFiles/lib.dir/src/loader/loader-query.cpp.o
[ 26%] Building CXX object lib/CMakeFiles/lib.dir/src/loader/loader.cpp.o
[ 26%] Building CXX object lib/CMakeFiles/lib.dir/src/loader/pack-loader.cpp.o
[ 28%] Building CXX object lib/CMakeFiles/lib.dir/src/loader/token.cpp.o
[ 28%] Building CXX object lib/CMakeFiles/lib.dir/src/logger.cpp.o
[ 28%] Building CXX object lib/CMakeFiles/lib.dir/src/login/http-basic-login.cpp.o
[ 28%] Building CXX object lib/CMakeFiles/lib.dir/src/login/http-get-login.cpp.o
[ 30%] Building CXX object lib/CMakeFiles/lib.dir/src/login/http-login.cpp.o
[ 30%] Building CXX object lib/CMakeFiles/lib.dir/src/login/http-post-login.cpp.o
[ 30%] Building CXX object lib/CMakeFiles/lib.dir/src/login/login.cpp.o
[ 31%] Building CXX object lib/CMakeFiles/lib.dir/src/login/oauth2-login.cpp.o
[ 31%] Building CXX object lib/CMakeFiles/lib.dir/src/login/url-login.cpp.o
[ 31%] Building CXX object lib/CMakeFiles/lib.dir/src/mixed-settings.cpp.o
[ 33%] Building CXX object lib/CMakeFiles/lib.dir/src/models/api/api.cpp.o
[ 33%] Building CXX object lib/CMakeFiles/lib.dir/src/models/api/javascript-api.cpp.o
[ 33%] Building CXX object lib/CMakeFiles/lib.dir/src/models/api/javascript-console-helper.cpp.o
[ 33%] Building CXX object lib/CMakeFiles/lib.dir/src/models/api/javascript-grabber-helper.cpp.o
[ 34%] Building CXX object lib/CMakeFiles/lib.dir/src/models/api/thread-safe-engine.cpp.o
[ 34%] Building CXX object lib/CMakeFiles/lib.dir/src/models/favorite.cpp.o
[ 34%] Building CXX object lib/CMakeFiles/lib.dir/src/models/filename.cpp.o
[ 36%] Building CXX object lib/CMakeFiles/lib.dir/src/models/filtering/blacklist.cpp.o
[ 36%] Building CXX object lib/CMakeFiles/lib.dir/src/models/filtering/filter-factory.cpp.o
[ 36%] Building CXX object lib/CMakeFiles/lib.dir/src/models/filtering/filter.cpp.o
[ 38%] Building CXX object lib/CMakeFiles/lib.dir/src/models/filtering/meta-filter.cpp.o
[ 38%] Building CXX object lib/CMakeFiles/lib.dir/src/models/filtering/post-filter.cpp.o
[ 38%] Building CXX object lib/CMakeFiles/lib.dir/src/models/filtering/tag-filter.cpp.o
[ 39%] Building CXX object lib/CMakeFiles/lib.dir/src/models/filtering/token-filter.cpp.o
[ 39%] Building CXX object lib/CMakeFiles/lib.dir/src/models/image-factory.cpp.o
[ 39%] Building CXX object lib/CMakeFiles/lib.dir/src/models/image-size.cpp.o
[ 39%] Building CXX object lib/CMakeFiles/lib.dir/src/models/image.cpp.o
[ 41%] Building CXX object lib/CMakeFiles/lib.dir/src/models/md5-database.cpp.o
[ 42%] Building CXX object lib/CMakeFiles/lib.dir/src/models/page-api.cpp.o
[ 42%] Building CXX object lib/CMakeFiles/lib.dir/src/models/monitor.cpp.o
[ 42%] Building CXX object lib/CMakeFiles/lib.dir/src/models/monitor-manager.cpp.o
[ 42%] Building CXX object lib/CMakeFiles/lib.dir/src/models/page.cpp.o
[ 42%] Building CXX object lib/CMakeFiles/lib.dir/src/models/pool.cpp.o
[ 44%] Building CXX object lib/CMakeFiles/lib.dir/src/models/profile.cpp.o
[ 44%] Building CXX object lib/CMakeFiles/lib.dir/src/models/search-query/gallery-search-query.cpp.o
In file included from /home/grabber/imgbrd-grabber/src/lib/src/models/image.cpp:20:0:
/home/grabber/imgbrd-grabber/src/lib/src/models/image.h: In constructor ‘Image::Image(Site*, QMap<QString, QString>, QVariantMap, Profile*, Page*)’:
/home/grabber/imgbrd-grabber/src/lib/src/models/image.h:148:14: warning: ‘Image::m_id’ will be initialized after [-Wreorder]
   qulonglong m_id;
              ^~~~
/home/grabber/imgbrd-grabber/src/lib/src/models/image.h:138:9: warning:   ‘Site* Image::m_parentSite’ [-Wreorder]
   Site *m_parentSite;
         ^~~~~~~~~~~~
/home/grabber/imgbrd-grabber/src/lib/src/models/image.cpp:82:1: warning:   when initialized here [-Wreorder]
 Image::Image(Site *site, QMap<QString, QString> details, QVariantMap data, Profile *profile, Page *parent)
 ^~~~~
In file included from /home/grabber/imgbrd-grabber/src/lib/src/models/image.cpp:20:0:
/home/grabber/imgbrd-grabber/src/lib/src/models/image.h:154:21: warning: ‘Image::m_extensionRotator’ will be initialized after [-Wreorder]
   ExtensionRotator *m_extensionRotator;
                     ^~~~~~~~~~~~~~~~~~
/home/grabber/imgbrd-grabber/src/lib/src/models/image.h:149:15: warning:   ‘QVariantMap Image::m_data’ [-Wreorder]
   QVariantMap m_data;
               ^~~~~~
/home/grabber/imgbrd-grabber/src/lib/src/models/image.cpp:82:1: warning:   when initialized here [-Wreorder]
 Image::Image(Site *site, QMap<QString, QString> details, QVariantMap data, Profile *profile, Page *parent)
 ^~~~~
[ 44%] Building CXX object lib/CMakeFiles/lib.dir/src/models/search-query/search-query.cpp.o
[ 46%] Building CXX object lib/CMakeFiles/lib.dir/src/models/site.cpp.o
[ 46%] Building CXX object lib/CMakeFiles/lib.dir/src/models/search-query/tag-search-query.cpp.o
[ 46%] Building CXX object lib/CMakeFiles/lib.dir/src/models/source-guesser.cpp.o
[ 46%] Building CXX object lib/CMakeFiles/lib.dir/src/models/source.cpp.o
[ 47%] Building CXX object lib/CMakeFiles/lib.dir/src/network/network-manager.cpp.o
[ 47%] Building CXX object lib/CMakeFiles/lib.dir/src/network/network-reply.cpp.o
[ 47%] Building CXX object lib/CMakeFiles/lib.dir/src/network/persistent-cookie-jar.cpp.o
[ 49%] Building CXX object lib/CMakeFiles/lib.dir/src/network/throttling-manager.cpp.o
[ 49%] Building CXX object lib/CMakeFiles/lib.dir/src/reverse-search/reverse-search-engine.cpp.o
[ 49%] Building CXX object lib/CMakeFiles/lib.dir/src/reverse-search/reverse-search-loader.cpp.o
[ 49%] Building CXX object lib/CMakeFiles/lib.dir/src/search/ast/search-node-op.cpp.o
[ 50%] Building CXX object lib/CMakeFiles/lib.dir/src/search/ast/search-node-tag.cpp.o
[ 50%] Building CXX object lib/CMakeFiles/lib.dir/src/search/search-format-visitor.cpp.o
[ 50%] Building CXX object lib/CMakeFiles/lib.dir/src/search/search-format.cpp.o
[ 52%] Building CXX object lib/CMakeFiles/lib.dir/src/secure-file.cpp.o
[ 52%] Building CXX object lib/CMakeFiles/lib.dir/src/tags/tag-api-base.cpp.o
[ 52%] Building CXX object lib/CMakeFiles/lib.dir/src/tags/tag-api.cpp.o
[ 53%] Building CXX object lib/CMakeFiles/lib.dir/src/tags/tag-database-factory.cpp.o
[ 53%] Building CXX object lib/CMakeFiles/lib.dir/src/tags/tag-database-in-memory.cpp.o
[ 53%] Building CXX object lib/CMakeFiles/lib.dir/src/tags/tag-database-sqlite.cpp.o
[ 55%] Building CXX object lib/CMakeFiles/lib.dir/src/tags/tag-database.cpp.o
[ 55%] Building CXX object lib/CMakeFiles/lib.dir/src/tags/tag-name-format.cpp.o
[ 55%] Building CXX object lib/CMakeFiles/lib.dir/src/tags/tag-name.cpp.o
[ 55%] Building CXX object lib/CMakeFiles/lib.dir/src/tags/tag-stylist.cpp.o
[ 57%] Building CXX object lib/CMakeFiles/lib.dir/src/tags/tag-type-api.cpp.o
[ 57%] Building CXX object lib/CMakeFiles/lib.dir/src/tags/tag-type-database.cpp.o
[ 57%] Building CXX object lib/CMakeFiles/lib.dir/src/tags/tag-type.cpp.o
[ 58%] Building CXX object lib/CMakeFiles/lib.dir/src/tags/tag.cpp.o
[ 58%] Building CXX object lib/CMakeFiles/lib.dir/src/updater/program-updater.cpp.o
[ 58%] Building CXX object lib/CMakeFiles/lib.dir/src/updater/source-updater.cpp.o
[ 60%] Building CXX object lib/CMakeFiles/lib.dir/src/updater/updater.cpp.o
[ 60%] Building CXX object lib/CMakeFiles/lib.dir/src/vendor/ganalytics.cpp.o
[ 60%] Building CXX object lib/CMakeFiles/lib.dir/src/vendor/html-entities.cpp.o
[ 61%] Building CXX object lib/CMakeFiles/lib.dir/src/vendor/simplecrypt.cpp.o
[ 61%] Building CXX object lib/CMakeFiles/lib.dir/src/vendor/qcustomnetworkreply.cpp.o
[ 61%] Building CXX object lib/CMakeFiles/lib.dir/lib_autogen/mocs_compilation.cpp.o
[ 61%] Linking CXX static library liblib.a
[ 61%] Built target lib
CMakeFiles/Makefile2:221: recipe for target 'gui/CMakeFiles/gui.dir/rule' failed
make[1]: *** [gui/CMakeFiles/gui.dir/rule] Error 2
Makefile:214: recipe for target 'gui' failed
make: *** [gui] Error 2
cp: cannot stat 'build/gui/Grabber': No such file or directory
cp: cannot stat 'build/languages/*.qm': No such file or directory
Grabber has been compiled in the release directory. To run it, type './release/Grabber'
```
The output says it was compiled but checking the release directory there are no files named "Grabber"

**Screenshots**

n/a

**System information**

- OS: Ubuntu 18.04.4 LTS x86_64
- Grabber version: 7.3.2

**Additional context**

I would like to build this for CLI, from what I know the build should just build for GUI which is fine but the way I see it is if it can't build the GUI there's no way it builds the CLI. Not to mention it's not very descriptive on how to build for CLI other than 
>When compiling Grabber, just uncomment “CONFIG += use_cli” to set the CLI to be the default behavior

but doesn't mention where to uncomment this from. Even GitHub can't find it
![image](https://user-images.githubusercontent.com/25551312/90817188-58b87480-e325-11ea-8114-db7d5d38b23b.png)

Note: I am fairly new to building things for Linux, but it appeared a lot easier than it seems.

**Comment by Bionus** [comment]
> E: Unable to correct problems, you have held broken packages.
>  npm ERR! typeerror This is an error with npm itself. Please report this error at:

I'd suggest upgrading your npm/node install, as simply doing apt-get install doesn't work in the build script, since it seems you have some broken/conflicting packages.

> I would like to build this for CLI, from what I know the build should just build for GUI which is fine but the way I see it is if it can't build the GUI there's no way it builds the CLI. Not to mention it's not very descriptive on how to build for CLI other than

If you want to build the CLI, just run `make cli` instide the `build` folder (where you ran `cmake`).
Also, the GUI also has CLI, it's just that you need to add `-c` and it might require an X server to run.

**Comment by Hi-ImKyle** [comment]
Yes updating NodeJS worked fine, but the compilation instructions doesn't specify a version for NodeJS so might want to add that.
