### ISSUE TITLE
Compile Error 

### ISSUE THREAD

**Issue by thisismycontributionaccount** [Bionus/imgbrd-grabber#2986]
I am getting a compile error during the typescript conversion process. I was trying to compile from the source since I was getting a different error trying to run the command line client on Linux.

**Steps to reproduce**
Run build.sh

Error produced:
[ 83%] Transpiling TypeScript sources into JavaScript...

> build
> tsc -p tsconfig.json

/private/anime/grabber/source/imgbrd-grabber-7.11.0/src/sites/node_modules/typescript/lib/tsc.js:93
  for (let i = startIndex ?? 0; i < array.length; i++) {
                           ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/private/anime/grabber/source/imgbrd-grabber-7.11.0/src/sites/node_modules/typescript/bin/tsc:2:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
make[3]: *** [sites/CMakeFiles/sites.dir/build.make:73: sites/JavaScript_sites] Error 1
make[2]: *** [CMakeFiles/Makefile2:1403: sites/CMakeFiles/sites.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:709: gui/CMakeFiles/gui.dir/rule] Error 2
make: *** [Makefile:329: gui] Error 2

**System information**

- OS: 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"

- Grabber version: 7.11.0

**Comment by Bionus** [comment]
You don't need `build.sh` if all you're doing is building sites, just `npm run build` in the `src/sites` directory is enough.
Is your TS file included in the `tsconfig.json`? Is the extension `.ts`?

**Comment by thisismycontributionaccount** [comment]
I was trying to build the whole thing from source. This was just the step that kept failing. When I tried running it by itself I get the same error:
$ npm run build

> build
> tsc -p tsconfig.json

/private/anime/grabber/source/imgbrd-grabber/src/sites/node_modules/typescript/lib/tsc.js:93
  for (let i = startIndex ?? 0; i < array.length; i++) {
                           ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/private/anime/grabber/source/imgbrd-grabber/src/sites/node_modules/typescript/bin/tsc:2:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

**Comment by Bionus** [comment]
Is your `node` version high enough?

Seems like you need at least node 14 for the `??` operator:
https://node.green/#ES2020-features--nullish-coalescing-operator-----

**Comment by thisismycontributionaccount** [comment]
Yep, that is what it was. The default system package on Ubuntu is to many releases behind.  You install it from the node.ls site. to get it to work.
